name: 'Build and deploy'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Environment'
        required: true
        
  

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Mandatory for OIDC/Workload Identity

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # This is the magic step that connects GitHub to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Docker Build result-image
      working-directory: ./helm-voting-code/result
      run: |
        docker build -t examplevotingapp_result_${{ github.event.inputs.tag}}
        docker images

